name: Testing
on: push

jobs:
  test_project:
    run-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: Set up Python 3.8
        uses: action/setup-python@v1
        with:
          python-version: 3.8
      -name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      -name: Run Django unit tests
          run: |
            python3 manage.py test
